### ISSUE TITLE
Viper Experiment

### ISSUE THREAD

**Issue by wangkaihong** [Huage001/Artistic-Video-Partial-Conv-Depth-Loss#1]
Hi Songhua,

I noticed that you mentioned the experiment on Viper dataset in your paper. I wonder how do you access to their occlusion masks for you temporal loss computation? It seems like they don't provide this modality.

Thanks.

**Comment by Huage001** [comment]
Hi Kaihong,

Thank you for your interest in the paper. Actually, all the optical flows and occlusion masks used for the experiments in our work are generated by [flownet2.0](https://github.com/NVIDIA/flownet2-pytorch) and a forward-backward consistency checker [here](https://github.com/manuelruder/artistic-videos/tree/master/consistencyChecker), except quantitative experiment in Tab. 1, where ground-truth flows and masks of Sintel dataset are used for evaluation.
